default_language_version:
  python: python3.9
repos:
- repo: https://github.com/PyCQA/flake8
  rev: "7.1.1"
  hooks:
  - id: flake8
    args: ["rbac"]
    pass_filenames: false
    require_serial: true
- repo: https://github.com/psf/black
  rev: 24.10.0
  hooks:
  - id: black
    args: ["--check", "-l", "119", "-t", "py39", "rbac", "tests", "--diff"]
    require_serial: true
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: debug-statements
- repo: https://github.com/casey-williams-rh/pipenv-pre-commit
  rev: v1.1.0
  hooks:
  - id: pipenv-generate-requirements
- repo: https://gitlab.cee.redhat.com/infosec-public/developer-workbench/tools.git
  rev: rh-pre-commit-2.3.0
  hooks:
    # If you have not run this hook on your system before, it may prompt you to
    # log in for patterns, and you will need to try again.
    #
    # Docs: https://source.redhat.com/departments/it/it-information-security/leaktk/leaktk_components/rh_pre_commit
    - id: rh-pre-commit
    # - id: rh-pre-commit.commit-msg # Optional for commit-msg attestation
